name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with: { python-version: '3.x' }
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install PySide6 pyinstaller
    - name: Build .app
      run: |
        pyinstaller --onefile --windowed --add-data "recipes.json:." Choix_cocktails.py
    - name: Zip and upload
      run: |
        ditto -c -k --sequesterRsrc --keepParent dist/Choix_cocktails.app ChoixCocktails-macos.zip
    - uses: actions/upload-artifact@v3
      with:
        name: choix-cocktails-macos
        path: ChoixCocktails-macos.zip
